### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by rugk** [Lanchon/haystack#11]
Is this project still maintained?

**Comment by Lanchon** [comment]
hmmm.... maintained? i don't understand the question... lol

well ok, i've been extremely busy. little less now, but still very. also i don't like haystack at all, and if i had time i'd prefer to improve dexpatcher. the reason i don't like it is here: https://github.com/Lanchon/haystack/issues/5#issuecomment-274549072

but anyway, let's pretend that i say yes, it's maintained, then what would you say next?

**Comment by rugk** [comment]
I would say: "Great. No recent commits, but we can have hope it works and issues will be fixed."

**Comment by Lanchon** [comment]
given work that @Nanolx is doing based on haystack, i sort of feel obligated to continue it.
