### ISSUE TITLE
Not working [7.1.2]

### ISSUE THREAD

**Issue by ElPumpo** [Lanchon/haystack#17]
I don't know what went wrong, but it's just not working! Followed the steps in the `README.md` file..
Nothing in the developer options, nothing :/

OPO with sultanxda's lineage ROM

[bulk-patch-builder.txt](https://github.com/Lanchon/haystack/files/1180623/bulk-patch-builder.txt)

**Comment by Lanchon** [comment]
lol i dont know either :)

you must be kidding me!!! no log of commands and their outputs??!!!!!!

**Comment by Lanchon** [comment]
i've updated DexPatcher to support Android 7.1, then updated Haystack for same.

**Comment by HawaiiBeach** [comment]
Ok gonna try it out now, and give u the logz this time 🥇

**Comment by HawaiiBeach** [comment]
Why is this bash scripts -_-, consider adding python scripts or something, I have a VM only to do this
and why did you revert 462225dc946af77e47679e00fe1f4565c3426d97

**Comment by HawaiiBeach** [comment]
[log.txt](https://github.com/Lanchon/haystack/files/1187392/log.txt)

I don't know what did the trick, but it works now! Thanks a lot for great stuff, man,
see ya around.

**Comment by Lanchon** [comment]
> Why is this bash scripts

why not??? don't use damn windows!!!!! or google linux subsystem for windows

> why did you revert

read the comment:
https://github.com/Lanchon/haystack/commit/dc136366a7f6d4c707a71dc67dbfcb0e22a5a297

**Comment by Lanchon** [comment]
> I don't know what did the trick, but it works now!

lol i think you just did it right this time :)
