### ISSUE TITLE
exception: lanchon.multidexlib2.EmptyMultiDexContainerException

### ISSUE THREAD

**Issue by MatthiasHGW** [Lanchon/haystack#18]
Hi!

Thank you for this great tool. I am trying to patch (the rooted) Android 7.1.1 on my Xperia Z5 compact. Pulling the files worked without problems, but when I applied the patch for the hook using 

./patch-fileset patches/sigspoof-hook-7.0-7.1/ 25 kompakt/

I get the following error message:

info: read 'kompakt/services.jar'
fatal: exception: lanchon.multidexlib2.EmptyMultiDexContainerException: kompakt/services.jar

I have to admit that I have no idea what this means. Could you please help me to solve this?

Thank you,
Matthias

**Comment by Lanchon** [comment]
hi,

as stated in the docs...

> Requirements:
> - An Android device **with a deodex rom** that supports root adb.

your rom is most likely not deodex.

**Comment by Lanchon** [comment]
maybe this helps? i don't know...

https://forum.xda-developers.com/showthread.php?t=2213235

**Comment by MatthiasHGW** [comment]
Thank you for the quick reply. I had read the requirement for a deodexed rom and checked if there are any *.odex files below /system/app. Since I could not find any, I had assumed that I am running a deodexed rom already. It seems that (with Nougat?) the *.odex files were replaced with *.oat files. I have spent the last hours trying to find out how to deodex my rom, but the more I read, the more confused I get. I will keep reading and then come back to haystack.

**Comment by MatthiasHGW** [comment]
So I have made some progress:
I found a way to deodex my rom using [superR's kitchen](https://forum.xda-developers.com/apps/superr-kitchen/kitchen-superr-s-kitchen-v1-1-50-v2-1-6-t3597434). Unfortunately, I was not able to produce a working system.img or even a full ROM zip. My phone got stuck during boot, so I

- used the deodexed core-libart.jar, core-oj.jar, ext.jar, framework.jar, services.jar and Settings.apk

- applied the patches succesfully

- Copied ext.jar, framework.jar, services.jar and Settings.apk into their corresponding directories on the phone. I had to do that manually (using a file manager), since "adb root" does not work on my phone, even though it is rooted.

- Rebooted.

- Sadly, "Allow signature spoofing" does not show up in my developer settings.

Is there a way to debug the patches somehow so I can find out what went wrong? Can I maybe activate Signature spoofing via adb, asuming that the patch itself is working and the problem is with the menu entry?

**Comment by Lanchon** [comment]
you CAN'T deodex partially: if you change one piece of code (like, by deodexing it) you invalidate ALL odexed code in the rom; deodexing is an all or nothing affair.

regarding your question, you can decide not to apply the UI (the 3rd) patch (it's optional), and spoofing will be always enabled.

it's easy to deodex a rom with smali directly, but there are lots of files to deodex and rebuild. there are tools to help (like the one you tried) but they must use the latest smali if you have nougat.

unfortunately, if you can't deodex your rom, you won't be able to patch it.

**Comment by MatthiasHGW** [comment]
Hi!

It took me a while, but I finally managed to deodex the complete ROM and flash it back to my phone. Applying your patches worked without any problems, and signature spoofing is "ENABLED" according to your Signature Spoofing Checker.
The only thing still missing is the UI. There is no entry in the developer options to disable signature spoofing. While I could live without it, it would be nice to have the full functionality of you patch. Is there a way for me to find out why I do not get the UI?

Thank you,
Matthias

**Comment by Lanchon** [comment]
hola Matt,

your issue is very weird. haystack patches are applied in 2 or 3 steps:
1) hook for a particular android version (required)
2) the signature spoofing code (required)
3) the UI (optional)

did you actually apply the 3rd patch? or have you forgotten? because when you apply the 3rd patch, the state of sigspoof becomes dependent on a setting, which by default is DISABLED. i can imagine a modded settings app that can be patched correctly... ok that could happen. what i don't get is then sigspoof to be ENABLED by default! (since you can't configure the setting.) this makes me very suspicious of your applying the 3rd patch. could you maybe have applied it but then pushed the wrong fileset to the phone?

thanks!

**Comment by MatthiasHGW** [comment]
Well, this is embarrassing! I just repeated the whole process and used your script to write the patched files back to the phone (I had copied them manually in my first attempt). Now everything works perfectly: signature spoofing and the GUI. Sorry for the confusion!
Thank you very much again for the patches and your support.

Matthias

**Comment by Lanchon** [comment]
thanks!
