### ISSUE TITLE
please add support for LG G2

### ISSUE THREAD

**Issue by eaglebooy** [Lanchon/haystack#21]
Hi this is first time i hear about faking google signature
my phone is too slow with google apps ( playstore and playservices )
i really want to use this patch , i need this patch , i try many times but get error

can you do patch for me?
here is the files
[https://mega.nz/#!cAdGlKzA!JAdAvJ1Z674BFMCyXX0dT-BDG_uj-F_zguf_39rO46s](url)

thanks alot for your help

**Comment by eaglebooy** [comment]
my error is

> 

 ./patch-fileset patches/sigspoof-hook-4.1-6.0/ 23 eaglll/
>>> target directory: eaglll__sigspoof-hook-4.1-6.0
>>> apply patch: services.jar
>>> dexpatcher --api-level 23 --verbose --output eaglll__sigspoof-hook-4.1-6.0/tmp/services.jar/patched-dex --multi-dex eaglll/services.jar patches/sigspoof-hook-4.1-6.0/services.jar.dex
/mnt/f/ROMS/+sign spoof/haystack-master/./.global: line 38: java: command not found

**Comment by Lanchon** [comment]
RTFM
