### ISSUE TITLE
How to enable signature spoofing without UI?

### ISSUE THREAD

**Issue by mixaz** [Lanchon/haystack#29]
Which command can I use to enable signature spoofing without UI part? It's disabled by default. Can I use a shell command for that, such as `adb shell setprop allow_fake_signature_global 1` (doesn't work just in case)?

**Comment by Lanchon** [comment]
there is no setting. it cant be enabled or disabled in any way. it is
always enabled.

**Comment by mixaz** [comment]
hm, the readme says that I need to go to Settings to enable this feature.
and indeed spoof checker app shows that it is disabled.

Can I enable the feature somehow from command line - I do not have
developer settings (it's very unusual custom rom)) ?

**Comment by mixaz** [comment]
My mistake was to use files which included UI patch. I should use files with core and hook patches only. Now the sigsproof checker shows OK.
Closing the issue.
