### ISSUE TITLE
Fatal exception when trying to apply hook patch

### ISSUE THREAD

**Issue by lionirdeadman** [Lanchon/haystack#30]
Log: 
```
./patch-fileset patches/sigspoof-hook-7.0-9.0/ 25 fs-tab-3/
>>> target directory: fs-tab-3__sigspoof-hook-7.0-9.0
>>> apply patch: services.jar
>>> dexpatcher --api-level 25 --verbose --output fs-tab-3__sigspoof-hook-7.0-9.0/tmp/services.jar/patched-dex --multi-dex fs-tab-3/services.jar patches/sigspoof-hook-7.0-9.0/services.jar.dex
DexPatcher version 1.6.2 by Lanchon (https://dexpatcher.github.io/)
info: read 'fs-tab-3/services.jar'
fatal: exception: lanchon.multidexlib2.EmptyMultiDexContainerException: fs-tab-3/services.jar
```

I'm unsure what else to put in this bug report, consider putting a template. I wish that'd be enough but I have a good feeling it's not so feel free to ask/request any and all things.

**Comment by Lanchon** [comment]
as per docs, you need a deodexed system. your system is odexed. google how to deodex it.

**Comment by lionirdeadman** [comment]
I have a LineageOS ROM, I would've thought it was already deodexed.. seems I gotta figure out how to deodex then. Thanks.

**Comment by JonnyTech** [comment]
@lionirdeadman, I use SuperR's kitchen to quickly and simply deodex ROM's: https://forum.xda-developers.com/apps/superr-kitchen

**Comment by lionirdeadman** [comment]
Thanks but SuperR's Kitchen is not something I'll be using due to the proprietary nature.

I think I'll simply wait for my NanoDroid issue to be fixed since deodexing is more complicated than I would've hoped.

**Comment by JonnyTech** [comment]
@lionirdeadman SuperR's Kitchen is open source: https://bitbucket.org/superr/superrs-kitchen/

There is a "donate" version, but the free open one does enough including deodexing..

**Comment by Lanchon** [comment]
nanolx patcher is nothing but haystack! repackaged to run in recovery, but still haystack. it wont work with a odexed rom.

**Comment by lionirdeadman** [comment]
NanoDroid's patcher is failing to deodex this particular ROM/Device as said [here](https://gitlab.com/Nanolx/NanoDroid/issues/83) (I actually have the same device/recovery/ROM combo)
