### ISSUE TITLE
disabled even if its not

### ISSUE THREAD

**Issue by jurek4321** [Lanchon/haystack#32]
Hey, i installed haystack on my sony z3c with lineageos 16 and newest stable magisk, i followed steps in the instruction and the "Signature spoofing" showed in the developers options but when i enable it the checker app still say that signature spoofing is disabled. I don't see allow_fake_signature_global in getprop command, i tried using "setprop allow_fake_signature_global 1" and then it showed in getprop command but it still say that signature spoofing is disabled in the checker app. Is there any way to fix it?

**Comment by Lanchon** [comment]
it should work. id need to see the full log of the operations you did (commands and outputs) and version of haystack used.

**Comment by Lanchon** [comment]
save your unpatched files to restore the system!

**Comment by Lanchon** [comment]
what version of the checker app r u using?

**Comment by jurek4321** [comment]
I had the latest version, now i installed carbonrom but i have backup and patched version somewhere on my disk i will find it.

**Comment by jurek4321** [comment]
there is backup and patched files https://drive.google.com/file/d/1BgZwByhYyAqROsm7zKpuP3Uq66dfb8Ex/view?usp=sharing

**Comment by Lanchon** [comment]
i don't want to investigate that. but if you want to, i can help.

if you want to investigate, patch the non-patched set again and give me:
- exact commands entered
- and exact output
 
and i'll tell you whats wrong.

otherwise please close this issue
thanks!

**Comment by jurek4321** [comment]
I have my zsh history from time when i was patching it, will it be ok?

**Comment by Lanchon** [comment]
no, i wouldn't know what the output was. i need this: https://github.com/Lanchon/haystack/issues/32#issuecomment-647920139

what do you want to accomplish, if i may ask? i thought u were using another rom now.

there's omni with microg built-in and regular omni plus minmicrog, if you want a ready made solution.

**Comment by jurek4321** [comment]
Ok, closing.
