### ISSUE TITLE
cp: illegal option -- t

### ISSUE THREAD

**Issue by vrindarx** [Lanchon/haystack#36]
When running ./patch-fileset command with the parameters, bash says 
`cp: illegal option -- t`

OS: macOS Monterey 12.5.1
Shell: zsh
Target device: Samsung Galaxy Tab 7 lite/v (T116-ny), Android 7.1.2 (API level 25), Lineage OS

**Comment by vrindarx** [comment]
It's this line that's the issue I guess
`cp -t "$patched_filterset_dir" "$fileset_dir"/*.{jar,apk}`

**Comment by vrindarx** [comment]
Ok found a fix, `cp -t` command allows reversed positions of arguments
`cp <from> <to>` becomes
`cp -t <to> <from>`

**Comment by Lanchon** [comment]
> Ok found a fix, `cp -t` command allows reversed positions of arguments `cp <from> <to>` becomes `cp -t <to> <from>`

nope, -t has a specific meaning. sorry but as descibed in the docs, macos is not supported. i dont support propietary software. nothing related to macos will be merged. but contrary to macos, this *is* free software, so you are free to fork.

**Comment by vrindarx** [comment]
> > Ok found a fix, `cp -t` command allows reversed positions of arguments `cp <from> <to>` becomes `cp -t <to> <from>`
> 
> nope, -t has a specific meaning. sorry but as descibed in the docs, macos is not supported. i dont support propietary software. nothing related to macos will be merged. but contrary to macos, this _is_ free software, so you are free to fork.

Oh ok sorry.
Also, just to let you know, it worked with macOS, Signature spoofing is working on my device.

I really love such brilliant pieces of code, thanks.

But just out of curiosity, can you tell me why did you use `-t` option? Just here to learn.

**Comment by Lanchon** [comment]
mv can be used to rename or move a file. if i remember correctly, -t asks for one or many files to be moved inside the specified directory. without -t only one file can be moved. and if the target does not already exists as a directory, it will move to a file with that name instead. without -t, mv tries to guess what you want from context and do something. it is not the best option for scripting. there are many mv calls in my code, and some might require -t for correctness.

**Comment by vrindarx** [comment]
> mv can be used to rename or move a file. if i remember correctly, -t asks for one or many files to be moved inside the specified directory. without -t only one file can be moved. and if the target does not already exists as a directory, it will move to a file with that name instead. without -t, mv tries to guess what you want from context and do something. it is not the best option for scripting. there are many mv calls in my code, and some might require -t for correctness. 

Oh ok thanks👍.

**Comment by rozhuk-im** [comment]
Same issue for FreeBSD.
Fix: ```cp "$fileset_dir"/*.{jar,apk} "$patched_filterset_dir/"```
