### ISSUE TITLE
failed to patch stage 3

### ISSUE THREAD

**Issue by bitching** [Lanchon/haystack#7]
Huawei EMUI 4.1.1 (Android 6.0)

[root@root haystack-master]# ./patch-fileset patches/sigspoof-ui-global-4.1-6.0/ 23 files__sigspoof-hook-4.1-6.0__sigspoof-core/
>>> target directory: files__sigspoof-hook-4.1-6.0__sigspoof-core__sigspoof-ui-global-4.1-6.0
>>> apply patch: Settings.apk
>>> dexpatcher --api-level 23 --verbose --output files__sigspoof-hook-4.1-6.0__sigspoof-core__sigspoof-ui-global-4.1-6.0/tmp/Settings.apk/patched-dex --multi-dex files__sigspoof-hook-4.1-6.0__sigspoof-core/Settings.apk patches/sigspoof-ui-global-4.1-6.0/Settings.apk.dex
info: read 'files__sigspoof-hook-4.1-6.0__sigspoof-core/Settings.apk'
info: read 'patches/sigspoof-ui-global-4.1-6.0/Settings.apk.dex'
error: type 'com.android.settings.DevelopmentSettings': direct method 'source_FakeSignatureGlobalUI_updateAllOptions():void': target 'updateAllOptions': (DevelopmentSettings.java:152): target not found
1 error(s), 0 warning(s)

**Comment by Lanchon** [comment]
hmmm...

the standard Settings app has a "com.android.settings.DevelopmentSettings::updateAllOptions() -> void" non-virtual method that the UI patch tries to hook.

this method is missing on your Huawei stock rom. you could mod the patch source and re compile it (i'm not going to do that), but i recommend that you just forgo the 3rd stage patch instead (the UI, which is optional), and just use the first 2 stages.

**Comment by bitching** [comment]
thx, any way stage 2 works!
