### ISSUE TITLE
'readlink: illegal option -f' on macOS

### ISSUE THREAD

**Issue by olliejm** [Lanchon/haystack#8]
I'm trying to patch the pulled fileset on macOS, but I'm getting the following error:

```
./patch-fileset patches/sigspoof-hook-7.0/ 23 fs-oneplus3t/
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
>>> target directory: fs-oneplus3t__sigspoof-hook-7.0
cp: illegal option -- t
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
```

It seems like readlink is deprecated on macOS or something, how should I proceed?

**Comment by simonepsp** [comment]
Hi,
essentially there are 2 issues :
- readlink doesn't have the -f option
- cp doesn't have the  -t option

To fix the _readlink_ issue you have to install greadlink via brew (`brew install coreutils`. Give a look here if you don't have Homebrew installed: https://brew.sh/index_it.html) and then replace "readlink" with "greadlink" in every haystack script. Alternatively you can run `alias readlink=greadlink`.

Now the cp issue: AFAIK macos' cp doesn't have the -t parameter. To fix this you have to replace `cp -t "$patched_filterset_dir" "$fileset_dir"/*.{jar,apk}` with  `cp $fileset_dir"/*.{jar,apk} $patched_filterset_dir` in the patch-fileset script.

I'm not a mac user but this should do the job.
Cheers!

**Comment by Lanchon** [comment]
thanks for the report. i don't support proprietary tools or OSes. you are on your own here, sorry for letting you down.
