### ISSUE TITLE
Can't dedex a rooted Galaxy S7

### ISSUE THREAD

**Issue by ghost** [Lanchon/haystack#9]
Keep getting this error:

$ ./dedex-fileset fs-galaxy fs-dedexed-galaxy
'>>>' target directory: fs-dedexed-galaxy
/path/to/haystack-master/./.global: line 44: d2j-dex2jar: command not found

Any ideas why?

**Comment by Lanchon** [comment]
because you don't have dex2jar installed:
https://github.com/Lanchon/haystack/blob/master/.global#L44

note that your device is probably odexed, so haystack will not work on it.

**Comment by Lanchon** [comment]
also note that dedexing is only needed to *build* your own patches, not to apply them. but i guess you know this. care to share what you are up to? :)

**Comment by ghost** [comment]
I wanted to install microG. I was hoping to work around the odex files.

**Comment by ghost** [comment]
I don't mind building my own patches, as I know some programming, but I need a good idea of where to start.

**Comment by Lanchon** [comment]
to use this tool (or Needle, or Tingle) you need a deodexed rom. you can use a custom rom that is not odexed, or you can deodex your rom. there are tools for deodexing. i've never used them because i don't use proprietary OSes of which i don't own the source code.

**Comment by ghost** [comment]
Can you recommend one?

**Comment by Lanchon** [comment]
lol no...

>  i've never used them because i don't use proprietary OSes of which i don't own the source code.
